
server:
  port: 8080
  
spring: 
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/personal_blog?characterEncoding=utf8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        #通过别名的方式配置扩展插件，常用的插件有： 
        #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
        filters: stat,wall,log4j
        #最大连接池数量
        maxActive: 20
        #初始化时建立物理连接的个数
        initialSize: 5
        #获取连接时最大等待时间
        maxWait: 60000
        #最小连接池数量
        minIdle: 1
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        #用来检测连接是否有效的sql，要求是一个查询语句
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
 
 

  

logging: 
  config: classpath:log4j2.xml
        
mybatis: 
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.winter.model  
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
